### ISSUE TITLE
[TECH] Stocker les appels en succès et pas seulement les erreurs

### ISSUE THREAD

**Issue by 3lodi3** [Immersion-Facilitee/immersion-facile#1804]
### :construction: Epic

#1746 

### :thinking: Contexte et problématique

Les conventions qui ont été en erreur mais ne le sont plus apparaissent toujours dans le tableau des conventions en erreur dans l'espace prescripteur.

### :tada: Proposition de solution

Story nécessaire pour pouvoir afficher uniquement les conventions toujours en erreur dans le tableau des conventions en erreur dans l'espace prescripteur : #1803

**Comment by nathalie-reyre** [comment]
duplica  ticket #1689
